VEUConfigScreen:
  AIR_FLOW_TAB_ASPIRATOR_SPEED:
    Index: 1
    WndClass: msctls_trackbar32
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_DELAY:
    Index: 18
    WndClass: Edit
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_FLOW_CHANGE:
    Index: 17
    WndClass: Edit
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_MAJOR_H1:
    Index: 1
    WndClass: Edit
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_MAJOR_H2:
    Index: 5
    WndClass: Edit
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_MAJOR_H3:
    Index: 9
    WndClass: Edit
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_MAJOR_H4:
    Index: 13
    WndClass: Edit
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_MAJOR_L1:
    Index: 4
    WndClass: Edit
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_MAJOR_L2:
    Index: 8
    WndClass: Edit
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_MAJOR_L3:
    Index: 12
    WndClass: Edit
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_MAJOR_L4:
    Index: 16
    WndClass: Edit
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_MINOR_H1:
    Index: 2
    WndClass: Edit
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_MINOR_H2:
    Index: 6
    WndClass: Edit
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_MINOR_H3:
    Index: 10
    WndClass: Edit
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_MINOR_H4:
    Index: 14
    WndClass: Edit
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_MINOR_L1:
    Index: 3
    WndClass: Edit
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_MINOR_L2:
    Index: 7
    WndClass: Edit
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_MINOR_L3:
    Index: 11
    WndClass: Edit
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_MINOR_L4:
    Index: 15
    WndClass: Edit
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_PIPES_1:
    WndCaption: '1'
    WndClass: Button
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_PIPES_2:
    WndCaption: '2'
    WndClass: Button
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_PIPES_3:
    WndCaption: '3'
    WndClass: Button
    parent:
    - detector_config_tabs
  AIR_FLOW_TAB_PIPES_4:
    WndCaption: '4'
    WndClass: Button
    parent:
    - detector_config_tabs
  ETHERNET_TAB_DEFAULT_GATEWAY:
    Index: 3
    WndClass: SysIPAddress32
    parent:
    - detector_config_tabs
  ETHERNET_TAB_DHCP:
    WndCaption: Automatically obtain IP Address (DHCP)
    WndClass: Button
    parent:
    - detector_config_tabs
  ETHERNET_TAB_IP_ADDRESS:
    Index: 1
    WndClass: SysIPAddress32
    parent:
    - detector_config_tabs
  ETHERNET_TAB_SUBNET_MASK:
    Index: 2
    WndClass: SysIPAddress32
    parent:
    - detector_config_tabs
  FILTER_TAB_SERVICE_INTERVAL:
    Index: 1
    WndClass: Edit
    parent:
    - detector_config_tabs
  FRIDAY_CHECKBOX:
    WndCaption: Friday
    WndClass: Button
    parent:
    - smoke_thresholds_tab_alarm_level_changeover
  GENERAL_PURPOSE_INPUTS_BUTTON_LOCKOUT:
    WndCaption: Button Lockout
    WndClass: Button
    parent:
    - detector_config_tabs
  GENERAL_PURPOSE_INPUTS_MONITERED:
    Index: 2
    WndClass: ComboBox
    parent:
    - detector_config_tabs
  GENERAL_PURPOSE_INPUTS_UNMONITERED:
    Index: 1
    WndClass: ComboBox
    parent:
    - detector_config_tabs
  GENERAL_TAB_ADDRESS:
    Index: 4
    WndClass: Edit
    parent:
    - detector_config_tabs
  GENERAL_TAB_LOCATION:
    Index: 2
    WndClass: Edit
    parent:
    - detector_config_tabs
  GENERAL_TAB_NETWORK_NAME:
    Index: 1
    WndClass: Edit
    parent:
    - detector_config_tabs
  GENERAL_TAB_SERIAL_NUMBER:
    Index: 3
    WndClass: Edit
    parent:
    - detector_config_tabs
  MONDAY_CHECKBOX:
    WndCaption: Monday
    WndClass: Button
    parent:
    - smoke_thresholds_tab_alarm_level_changeover
  REFERENCING_TAB_DELAY:
    Index: 1
    WndClass: Edit
    parent:
    - detector_config_tabs
  REFERENCING_TAB_DETECTOR:
    Index: 1
    WndClass: ComboBox
    parent:
    - detector_config_tabs
  REFERENCING_TAB_DILUTION_FACTOR:
    Index: 2
    WndClass: Edit
    parent:
    - detector_config_tabs
  REFERENCING_TAB_REFERENCING_ENABLE:
    WndCaption: Referencing Enabled
    WndClass: Button
    parent:
    - detector_config_tabs
  SATURDAY_CHECKBOX:
    WndCaption: Saturday
    WndClass: Button
    parent:
    - smoke_thresholds_tab_alarm_level_changeover
  SMOKE_THRESHOLDS_ACTION_D:
    Index: 5
    WndClass: Edit
    parent:
    - detector_config_tabs
  SMOKE_THRESHOLDS_ACTION_DELAY:
    Index: 11
    WndClass: Edit
    parent:
    - detector_config_tabs
  SMOKE_THRESHOLDS_ACTION_N:
    Index: 6
    WndClass: Edit
    parent:
    - detector_config_tabs
  SMOKE_THRESHOLDS_ALERT_D:
    Index: 7
    WndClass: Edit
    parent:
    - detector_config_tabs
  SMOKE_THRESHOLDS_ALERT_DELAY:
    Index: 12
    WndClass: Edit
    parent:
    - detector_config_tabs
  SMOKE_THRESHOLDS_ALERT_N:
    Index: 8
    WndClass: Edit
    parent:
    - detector_config_tabs
  SMOKE_THRESHOLDS_CUMULATIVE_DELAY:
    WndCaption: Cumulative Delay
    WndClass: Button
    parent:
    - detector_config_tabs
  SMOKE_THRESHOLDS_DAYNIGHT_ENABLE:
    WndCaption: Enabled
    WndClass: Button
    parent:
    - smoke_thresholds_tab_alarm_level_changeover
  SMOKE_THRESHOLDS_DAY_START:
    Index: 1
    WndClass: Edit
    parent:
    - smoke_thresholds_tab_alarm_level_changeover
  SMOKE_THRESHOLDS_END_HOLIDAY:
    Index: 2
    WndClass: SysDateTimePick32
    parent:
    - smoke_thresholds_tab_alarm_level_changeover
  SMOKE_THRESHOLDS_F1_D:
    Index: 3
    WndClass: Edit
    parent:
    - detector_config_tabs
  SMOKE_THRESHOLDS_F1_DELAY:
    Index: 10
    WndClass: Edit
    parent:
    - detector_config_tabs
  SMOKE_THRESHOLDS_F1_N:
    Index: 4
    WndClass: Edit
    parent:
    - detector_config_tabs
  SMOKE_THRESHOLDS_F2_D:
    Index: 1
    WndClass: Edit
    parent:
    - detector_config_tabs
  SMOKE_THRESHOLDS_F2_DELAY:
    Index: 9
    WndClass: Edit
    parent:
    - detector_config_tabs
  SMOKE_THRESHOLDS_F2_N:
    Index: 2
    WndClass: Edit
    parent:
    - detector_config_tabs
  SMOKE_THRESHOLDS_HOLIDAY:
    WndCaption: Enabled
    WndClass: Button
    parent:
    - smoke_thresholds_tab_alarm_level_changeover
  SMOKE_THRESHOLDS_INSTANT_FIRE:
    WndCaption: Instant Fire
    WndClass: Button
    parent:
    - detector_config_tabs
  SMOKE_THRESHOLDS_LOGGING:
    Index: 13
    WndClass: Edit
    parent:
    - detector_config_tabs
  SMOKE_THRESHOLDS_NIGHT_START:
    Index: 2
    WndClass: Edit
    parent:
    - smoke_thresholds_tab_alarm_level_changeover
  SMOKE_THRESHOLDS_START_HOLIDAY:
    Index: 1
    WndClass: SysDateTimePick32
    parent:
    - smoke_thresholds_tab_alarm_level_changeover
  SMOKE_THRESHOLDS_VESDANET:
    Index: 14
    WndClass: Edit
    parent:
    - detector_config_tabs
  SUNDAY_CHECKBOX:
    WndCaption: Sunday
    WndClass: Button
    parent:
    - smoke_thresholds_tab_alarm_level_changeover
  THURSDAY_CHECKBOX:
    WndCaption: Thursday
    WndClass: Button
    parent:
    - smoke_thresholds_tab_alarm_level_changeover
  TUESDAY_CHECKBOX:
    WndCaption: Tuesday
    WndClass: Button
    parent:
    - smoke_thresholds_tab_alarm_level_changeover
  VESDANET_TAB_LOOP:
    WndCaption: 'Loop open ended on this device.*'
    WndClass: Button
    parent:
    - detector_config_tabs
  VESDANET_TAB_MINIMUM_INTERVAL:
    Index: 1
    WndClass: Edit
    parent:
    - detector_config_tabs
  VESDANET_TAB_PORT_A:
    WndCaption: Port A
    WndClass: Button
    parent:
    - detector_config_tabs
  VESDANET_TAB_PORT_B:
    WndCaption: Port B
    WndClass: Button
    parent:
    - detector_config_tabs
  WEDNESDAY_CHECKBOX:
    WndCaption: Wednesday
    WndClass: Button
    parent:
    - smoke_thresholds_tab_alarm_level_changeover
  WIFI_TAB_DEFAULT_GATEWAY:
    Index: 3
    WndClass: SysIPAddress32
    parent:
    - detector_config_tabs
  WIFI_TAB_DHCP:
    WndCaption: Automatically obtain IP Address (DHCP)
    WndClass: Button
    parent:
    - detector_config_tabs
  WIFI_TAB_ENABLE:
    WndCaption: WiFi Enabled
    WndClass: Button
    parent:
    - detector_config_tabs
  WIFI_TAB_IP_ADDRESS:
    Index: 1
    WndClass: SysIPAddress32
    parent:
    - detector_config_tabs
  WIFI_TAB_SECURITY_MODE:
    Index: 1
    WndClass: ComboBox
    parent:
    - detector_config_tabs
  WIFI_TAB_SHOW_TEXT:
    WndCaption: Show Text
    WndClass: Button
    parent:
    - detector_config_tabs
  WIFI_TAB_SSID:
    Index: 1
    WndClass: Edit
    parent:
    - detector_config_tabs
  WIFI_TAB_SUBNET_MASK:
    Index: 2
    WndClass: SysIPAddress32
    parent:
    - detector_config_tabs
  WIFI_TAB_WEP_KEY:
    Index: 2
    WndClass: Edit
    parent:
    - detector_config_tabs
  apply_button:
    WndCaption: "*Apply"
    WndClass: Button
  cancel_button:
    WndCaption: "*Cancel"
    WndClass: Button
  detector_config:
    Index: 1
    WndCaption: VESDA *
    WndClass: '#32770'
  detector_config_tabs:
    Index: 1
    WndClass: '#32770'
    parent:
    - detector_config
  help_button:
    WndCaption: "*Help"
    WndClass: Button
  ok_button:
    WndCaption: "*OK"
    WndClass: Button
  smoke_thresholds_tab_alarm_level_changeover:
    Index: 1
    WndClass: '#32770'
    parent:
    - detector_config_tabs
  tab:
    Index: 1
    WndClass: SysTabControl32
